import "./globals.css";
/* TOASTIFY */
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import Footer from "./components/Footer";
import Header from "./components/Header";
import { getAppInfo } from "@/api/getAppInfo";

export const metadata = {
  title: "Royals",
  description: "Generated by create next app",
};



export default async function RootLayout({ children }) {
  const appInfoData = await getAppInfo();

  return (
    <html lang="en">
      <body>
        
        <Header />
        
        {children}
        
        <Footer appInfoData={appInfoData} />
        
        <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored" />
      </body>
    </html>
  );
}
